### ISSUE TITLE
Highlight which slide I am working on in the editor

### ISSUE THREAD

**Issue by manikani** [pxi-gmbh/slidenotes#2]
## description
In the editor textfield, I want to see even more clearly where one slide starts and it ends.

## proposed change
Highlight the background of the text of the one slide where my caret is at the moment.

## caveats
The solution must not increase the rendering time.

## additional information
Instead of highlighting the one slide I am working on, you could also reduce the visibility of the slides I am not working on at the moment.

**Comment by jochmann** [comment]
has been added in most recent update.
